### ISSUE TITLE
Connecting issue

### ISSUE THREAD

**Issue by raqbit** [bl4ckscor3/bl4ckChat#1]
```
java.lang.RuntimeException: Exception encountered when writing to socket
    at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:303)
    at org.pircbotx.Utils.sendRawLineToServer(Utils.java:88)
    at org.pircbotx.output.OutputRaw.rawLineNow(OutputRaw.java:105)
    at org.pircbotx.output.OutputRaw.rawLineNow(OutputRaw.java:90)
    at org.pircbotx.PircBotX.connect(PircBotX.java:232)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:151)
    at bl4ckscor3.misc.bl4ckchat.listener.ButtonListener.lambda$0(ButtonListener.java:102)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)
    at sun.security.ssl.InputRecord.read(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
    at sun.security.ssl.AppOutputStream.write(Unknown Source)
    at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
    at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
    at sun.nio.cs.StreamEncoder.flush(Unknown Source)
    at java.io.OutputStreamWriter.flush(Unknown Source)
    at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:300)
    ... 20 more
```

To reproduce: Just try to connect

**Comment by raqbit** [comment]
There are actually multiple stacktraces to it, but I sent the last one

**Comment by bl4ckscor3** [comment]
Ah, that is simple. You selected the checkbox to use ssl, but haven't actually put in the correct SSL port.

**Comment by raqbit** [comment]
Hmm.. I think it did the same when not checking that. Oh well. I'll check tomorrow.

**Comment by bl4ckscor3** [comment]
I've actually found the issue now...
Sorry for my nonsense earlier. I'll close as soon as I have the fixing commit.
